version: '3.8'
 
services:
  nextjs-app:
    image: hamza971/nextjs-hamza:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - nextjs-data:/app/.next
    restart: unless-stopped
 
volumes:
  nextjs-data: